### ISSUE TITLE
Upgrade to Deno 1.8.0

### ISSUE THREAD

**Issue by rracariu** [KSXGitHub/deno-args#67]
On Deno 1.8.0 there is a compilation error.

```
error: TS2322 [ERROR]: Type '(args: readonly ArgvItem[]) => Ok<{ value: undefined; consumedFlags: Set<unknown>; }>' is not assignable to type '(args: readonly ArgvItem[]) => Result<{ value: void; consumedFlags: ReadonlySet<ArgvItem>; }, FlagError>'.
  Type 'Ok<{ value: undefined; consumedFlags: Set<unknown>; }>' is not assignable to type 'Result<{ value: void; consumedFlags: ReadonlySet<ArgvItem>; }, FlagError>'.
    Type 'Ok<{ value: undefined; consumedFlags: Set<unknown>; }>' is not assignable to type 'Ok<{ value: void; consumedFlags: ReadonlySet<ArgvItem>; }>'.
      Type '{ value: undefined; consumedFlags: Set<unknown>; }' is not assignable to type '{ value: void; consumedFlags: ReadonlySet<ArgvItem>; }'.
        The types of 'consumedFlags.forEach' are incompatible between these types.
          Type '(callbackfn: (value: unknown, value2: unknown, set: Set<unknown>) => void, thisArg?: any) => void' is not assignable to type '(callbackfn: (value: ArgvItem, value2: ArgvItem, set: ReadonlySet<ArgvItem>) => void, thisArg?: any) => void'.
            Types of parameters 'callbackfn' and 'callbackfn' are incompatible.
              Types of parameters 'value' and 'value' are incompatible.
                Type 'unknown' is not assignable to type 'ArgvItem'.
                  Type 'unknown' is not assignable to type 'Value'.
  extract(args) {
  ~~~~~~~
    at https://deno.land/x/args@2.0.7/flag-types.ts:81:3

    The expected type comes from property 'extract' which is declared here on type 'FlagType<Name, void>'
      extract(args: readonly ArgvItem[]): Result<{
      ^
        at https://deno.land/x/args@2.0.7/types.ts:18:3
```

**Comment by KSXGitHub** [comment]
Can you let me see your code?

**Comment by KSXGitHub** [comment]
[2.0.8](https://deno.land/x/args@2.0.8)
